### ISSUE TITLE
RuntimeError: CUDA Error encountered in <function CompiledLib.bn_mean_var_cuda at 0x7fe370c31620>

### ISSUE THREAD

**Issue by csjunxu** [speedinghzl/pytorch-segmentation-toolbox#30]
321300 images are loaded!
Traceback (most recent call last):
  File "train.py", line 251, in <module>
    main()
  File "train.py", line 215, in main
    preds = model(images)
  File "/home/xj1/anaconda3/envs/segtool/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/xj1/anaconda3/envs/segtool/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 114, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/xj1/anaconda3/envs/segtool/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 124, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/xj1/anaconda3/envs/segtool/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 65, in parallel_apply
    raise output
  File "/home/xj1/anaconda3/envs/segtool/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 41, in _worker
    output = module(*input, **kwargs)
  File "/home/xj1/anaconda3/envs/segtool/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/xj1/pytorch-segmentation-toolbox/networks/pspnet.py", line 139, in forward
    x = self.relu1(self.bn1(self.conv1(x)))
  File "/home/xj1/anaconda3/envs/segtool/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/xj1/pytorch-segmentation-toolbox/libs/bn.py", line 184, in forward
    self.activation, self.slope)
  File "/home/xj1/pytorch-segmentation-toolbox/libs/functions.py", line 183, in forward
    _check(_ext.bn_mean_var_cuda, x, mean, var)
  File "/home/xj1/pytorch-segmentation-toolbox/libs/functions.py", line 16, in _check
    raise RuntimeError("CUDA Error encountered in {}".format(fn))
RuntimeError: CUDA Error encountered in <function CompiledLib.bn_mean_var_cuda at 0x7fe370c31620>

**Comment by chenyzh28** [comment]
How did you solve it?
