### ISSUE TITLE
python build.py error?

### ISSUE THREAD

**Issue by suyanzhou626** [speedinghzl/pytorch-segmentation-toolbox#5]
(pytorch-0.41_2) lsy@lsy-pc:/media/lsy/syz/pytorch-segmentation-toolbox/libs$ python build.py
generating /tmp/tmp613dsnl4/__ext.c
setting the current directory to '/tmp/tmp613dsnl4'
running build_ext
building '__ext' extension
creating media
creating media/lsy
creating media/lsy/syz
creating media/lsy/syz/pytorch-segmentation-toolbox
creating media/lsy/syz/pytorch-segmentation-toolbox/libs
creating media/lsy/syz/pytorch-segmentation-toolbox/libs/src
gcc -pthread -B /home/lsy/miniconda3/envs/pytorch-0.41_2/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/media/lsy/syz/pytorch-segmentation-toolbox/libs/../../lib/include -I/media/lsy/syz/pytorch-segmentation-toolbox/libs/../../lib/include/TH -I/media/lsy/syz/pytorch-segmentation-toolbox/libs/../../lib/include/THC -I/usr/local/cuda/include -I/home/lsy/miniconda3/envs/pytorch-0.41_2/include/python3.6m -c __ext.c -o ./__ext.o -std=c99 -std=c++11
cc1: warning: command line option ‘-std=c++11’ is valid for C++/ObjC++ but not for C
__ext.c:492:19: fatal error: TH/TH.h: No such file or directory
compilation terminated.
Traceback (most recent call last):
  File "/home/lsy/miniconda3/envs/pytorch-0.41_2/lib/python3.6/distutils/unixccompiler.py", line 118, in _compile
    extra_postargs)
  File "/home/lsy/miniconda3/envs/pytorch-0.41_2/lib/python3.6/distutils/ccompiler.py", line 909, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "/home/lsy/miniconda3/envs/pytorch-0.41_2/lib/python3.6/distutils/spawn.py", line 36, in spawn
    _spawn_posix(cmd, search_path, dry_run=dry_run)
  File "/home/lsy/miniconda3/envs/pytorch-0.41_2/lib/python3.6/distutils/spawn.py", line 159, in _spawn_posix
    % (cmd, exit_status))
distutils.errors.DistutilsExecError: command 'gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lsy/miniconda3/envs/pytorch-0.41_2/lib/python3.6/site-packages/cffi/ffiplatform.py", line 51, in _build
    dist.run_command('build_ext')
  File "/home/lsy/miniconda3/envs/pytorch-0.41_2/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/lsy/miniconda3/envs/pytorch-0.41_2/lib/python3.6/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/home/lsy/miniconda3/envs/pytorch-0.41_2/lib/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "/home/lsy/miniconda3/envs/pytorch-0.41_2/lib/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/lsy/miniconda3/envs/pytorch-0.41_2/lib/python3.6/distutils/command/build_ext.py", line 533, in build_extension
    depends=ext.depends)
  File "/home/lsy/miniconda3/envs/pytorch-0.41_2/lib/python3.6/distutils/ccompiler.py", line 574, in compile
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
  File "/home/lsy/miniconda3/envs/pytorch-0.41_2/lib/python3.6/distutils/unixccompiler.py", line 120, in _compile
    raise CompileError(msg)
distutils.errors.CompileError: command 'gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "build.py", line 24, in <module>
    ffi.build()
  File "/media/lsy/syz/pytorch-segmentation-toolbox/libs/ffi.py", line 189, in build
    _build_extension(ffi, cffi_wrapper_name, target_dir, verbose)
  File "/media/lsy/syz/pytorch-segmentation-toolbox/libs/ffi.py", line 111, in _build_extension
    outfile = ffi.compile(tmpdir=tmpdir, verbose=verbose, target=libname)
  File "/home/lsy/miniconda3/envs/pytorch-0.41_2/lib/python3.6/site-packages/cffi/api.py", line 697, in compile
    compiler_verbose=verbose, debug=debug, **kwds)
  File "/home/lsy/miniconda3/envs/pytorch-0.41_2/lib/python3.6/site-packages/cffi/recompiler.py", line 1520, in recompile
    compiler_verbose, debug)
  File "/home/lsy/miniconda3/envs/pytorch-0.41_2/lib/python3.6/site-packages/cffi/ffiplatform.py", line 22, in compile
    outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
  File "/home/lsy/miniconda3/envs/pytorch-0.41_2/lib/python3.6/site-packages/cffi/ffiplatform.py", line 58, in _build
    raise VerificationError('%s: %s' % (e.__class__.__name__, e))
cffi.error.VerificationError: CompileError: command 'gcc' failed with exit status 1

how to solve it?
cuda version: cuda 9.0
pytorch version: 0.41

**Comment by speedinghzl** [comment]
Hi, @suyanzhou626 you might want to check which arch your GPU is and modify build.sh to adapt your GPU.

**Comment by foolwood** [comment]
-gencode=arch=compute_70,code=sm_70 \
@suyanzhou626
